version: '3.8'

services:
  formula-recognition:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formula-recognition-api
    ports:
      - "8000:8080"
    volumes:
      # Mount for development
      - ./src:/app/src
      - ./trained-model:/app/trained-model
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      # Set log level
      - LOG_LEVEL=INFO
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    # GPU support (uncomment if you have NVIDIA GPU)
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    
    # Alternative GPU support for newer Docker versions
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Optional: Add nginx reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: formula-recognition-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - formula-recognition
  #   restart: unless-stopped

# Create networks
networks:
  default:
    name: formula-recognition-network

volumes:
  model_data:
    driver: local
  logs:
    driver: local